title: music-resources
description:  A curated list of free/pay-what-you-want plugins and tools for musicians :) 
theme: just-the-docs

url: https://liliantdn.github.io/music-resources/

aux_links:
  Github: https://github.com/liliantdn/music-resources
